name: Metrics
on:
  schedule: [{cron: "0 */3 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 7
          plugin_achievements: yes
          plugin_activity: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_lines: yes
          plugin_people: yes
          plugin_reactions: yes
          plugin_reactions_details: count, percentage
          plugin_stars: yes
